"""
Gmail integration for KPPP daily summary emails.

Fetches PDF attachments from KPPP daily summary emails received since
`since_date`, parses the tender table from each PDF, and returns a
canonical list of tender dicts matching the schema in browser.py.

Environment variables (set via GitHub Secrets in CI):
    GMAIL_CLIENT_ID
    GMAIL_CLIENT_SECRET
    GMAIL_REFRESH_TOKEN

For local use, token.json is used if present (generated by scripts/get_token.py).
"""

import base64
import io
import logging
import os
import re
from datetime import date, datetime
from pathlib import Path

import pdfplumber
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

log = logging.getLogger(__name__)

SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]
TOKEN_FILE = Path(__file__).parent.parent / "token.json"

# KPPP sends from this address — tighten the search if needed
KPPP_SENDER = "kppp"


def _get_credentials() -> Credentials:
    """Build credentials from env vars (CI) or token.json (local)."""
    client_id = os.getenv("GMAIL_CLIENT_ID")
    client_secret = os.getenv("GMAIL_CLIENT_SECRET")
    refresh_token = os.getenv("GMAIL_REFRESH_TOKEN")

    if client_id and client_secret and refresh_token:
        creds = Credentials(
            token=None,
            refresh_token=refresh_token,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=client_id,
            client_secret=client_secret,
            scopes=SCOPES,
        )
        creds.refresh(Request())
        return creds

    if TOKEN_FILE.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
        return creds

    raise RuntimeError(
        "No Gmail credentials found. Set GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, "
        "GMAIL_REFRESH_TOKEN env vars, or run scripts/get_token.py locally."
    )


def fetch_tenders_from_email(since_date: date) -> list[dict]:
    """
    Search Gmail for KPPP daily summary emails since `since_date`,
    download PDF attachments, parse tender tables, and return
    a deduplicated list of canonical tender dicts.
    """
    creds = _get_credentials()
    service = build("gmail", "v1", credentials=creds, cache_discovery=False)

    since_str = since_date.strftime("%Y/%m/%d")
    query = f"from:{KPPP_SENDER} has:attachment filename:pdf after:{since_str}"
    log.info(f"Gmail search query: {query}")

    results = service.users().messages().list(userId="me", q=query, maxResults=20).execute()
    messages = results.get("messages", [])
    log.info(f"Found {len(messages)} KPPP email(s) since {since_date}")

    all_tenders: list[dict] = []
    for msg_ref in messages:
        msg = service.users().messages().get(userId="me", id=msg_ref["id"], format="full").execute()
        pdfs = _extract_pdf_attachments(service, msg)
        for pdf_name, pdf_bytes in pdfs:
            log.info(f"Parsing PDF: {pdf_name} ({len(pdf_bytes):,} bytes)")
            tenders = _parse_pdf(pdf_bytes, pdf_name)
            log.info(f"  → {len(tenders)} tenders extracted")
            all_tenders.extend(tenders)

    return _deduplicate(all_tenders, "tender_number")


def _extract_pdf_attachments(service, message: dict) -> list[tuple[str, bytes]]:
    """Return list of (filename, bytes) for all PDF attachments in a message."""
    pdfs = []
    msg_id = message["id"]

    def _walk(parts):
        for part in parts:
            if part.get("parts"):
                _walk(part["parts"])
                continue
            mime = part.get("mimeType", "")
            filename = part.get("filename", "")
            if "pdf" not in mime.lower() and not filename.lower().endswith(".pdf"):
                continue
            body = part.get("body", {})
            attachment_id = body.get("attachmentId")
            if attachment_id:
                att = service.users().messages().attachments().get(
                    userId="me", messageId=msg_id, id=attachment_id
                ).execute()
                data = base64.urlsafe_b64decode(att["data"])
            elif body.get("data"):
                data = base64.urlsafe_b64decode(body["data"])
            else:
                continue
            pdfs.append((filename or "attachment.pdf", data))

    payload = message.get("payload", {})
    if payload.get("parts"):
        _walk(payload["parts"])
    return pdfs


def _parse_pdf(pdf_bytes: bytes, source_name: str) -> list[dict]:
    """Extract tender rows from a KPPP daily summary PDF."""
    tenders = []
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            table = page.extract_table()
            if not table:
                continue
            for row in table:
                # Skip header rows (first cell contains "Department")
                if not row or not row[0]:
                    continue
                first_cell = str(row[0]).strip()
                if "Department" in first_cell and "Location" in first_cell:
                    continue
                tender = _normalize_row(row)
                if tender.get("tender_number"):
                    tenders.append(tender)
    return tenders


def _normalize_row(row: list) -> dict:
    """
    Map a PDF table row to the canonical tender schema.

    PDF columns:
    [0] Department - Location
    [1] Tender Number
    [2] Tender Category
    [3] Tender Title
    [4] Estimate Value
    [5] NIT Published Date
    [6] Last Date for Bid Submission
    """
    def cell(i: int) -> str:
        if i >= len(row) or row[i] is None:
            return ""
        return re.sub(r"\s+", " ", str(row[i])).strip()

    dept_location = cell(0)
    # Split "Department Name - Location Name" on the last " - "
    dept, district = "", ""
    if " - " in dept_location:
        parts = dept_location.rsplit(" - ", 1)
        dept, district = parts[0].strip(), parts[1].strip()
    else:
        dept = dept_location

    tender_number = re.sub(r"\s+", "", cell(1))  # remove spaces from PDF line-wrapping
    category = cell(2)
    title = cell(3)
    ecv_raw = cell(4)
    published_date = _parse_date(cell(5))
    deadline = _parse_date(cell(6))

    nit_id = _extract_nit_id(tender_number, category)
    nit_url = (
        f"https://kppp.karnataka.gov.in/#/portal/tender-view/{nit_id}/{category.lower()}"
        if nit_id else ""
    )

    return {
        "tender_number": tender_number,
        "title": title,
        "description": "",
        "department": dept,
        "district": district,
        "category": category,
        "sub_category": "",
        "ecv": _parse_ecv(ecv_raw),
        "published_date": published_date,
        "deadline": deadline,
        "status": "Published",
        "nit_url": nit_url,
        "source": "email",
    }


def _parse_date(raw: str) -> str:
    """Normalize date strings from the PDF to YYYY-MM-DD."""
    if not raw:
        return ""
    # Try "2026-04-25 21:13:06" format
    m = re.match(r"(\d{4}-\d{2}-\d{2})", raw)
    if m:
        return m.group(1)
    return raw


def _extract_nit_id(tender_number: str, category: str) -> str:
    """
    The KPPP portal tender-view URL uses a numeric NIT ID, not the tender number.
    We can't reliably derive it from the PDF, so leave blank for now.
    Users can still search by tender number on the portal.
    """
    return ""


def _parse_ecv(raw: str) -> float | None:
    if not raw or raw.strip() in ("---", "-", "N/A", "nil", ""):
        return None
    s = re.sub(r"[₹,\s]", "", raw)
    s_lower = s.lower()
    try:
        if "crore" in s_lower:
            return float(re.sub(r"[^0-9.]", "", s_lower.replace("crores", "").replace("crore", ""))) * 1e7
        if "lakh" in s_lower:
            return float(re.sub(r"[^0-9.]", "", s_lower.replace("lakhs", "").replace("lakh", ""))) * 1e5
        val = float(re.sub(r"[^0-9.]", "", s))
        return val if val > 0 else None
    except ValueError:
        return None


def _deduplicate(tenders: list[dict], key: str) -> list[dict]:
    seen: set[str] = set()
    result = []
    for t in tenders:
        k = t.get(key, "")
        if k and k in seen:
            continue
        if k:
            seen.add(k)
        result.append(t)
    return result
